# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = /home/thomaz/Applications/ToolHive-39.2.7-x86_64_1787e0deecd7e189c9d36c0c2fdad3ce.AppImage
exec-once = thv start toolhive-mcp-optimizer