# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
# Global transparency and blur (applied to all windows)
windowrule = opacity 0.8 0.8, match:class .*
windowrule = no_blur off, match:class .*

# --- Exclusions for Streaming and Video (Opaque and no blur interference) ---
windowrule = opacity 1.0 1.0, match:class ^(vlc|mpv|stremio|Spotify|FreeTube)$
windowrule = opacity 1.0 1.0, match:title ^(.*)(YouTube|Netflix|Disney\+|Prime Video|Twitch)(.*)$
windowrule = no_blur on, match:class ^(vlc|mpv|stremio)$
